# Don't commit this file to your repository.

# =========REQUIRED FIELDS=========
# Your secret bot token.
bot_token: <secret_bot_token>

# Your discord server ID
server_id: <discord_server_id>

# Set to true if you want to use snake, sword, axe emojis, rather than number emojis
use_icon_emojis: true


# =========GOOGLE SHEETS (OPTIONAL)=========
# Set to true to use google sheets integration (totally hacked together)
use_google_sheets: false

# Path to the Google Application Service Account Credentials File (tm) (c) (r)
google_service_account_creds: <credentials_file>

# URL to the Google Sheets that will have all the player sheets
google_sheets_url: <google_sheets_url>
